import assert from 'node:assert/strict';
import { Notebook, mergeNotes, syncNotes } from '../web/js/notebook.js';
import { api, ConflictError } from '../web/js/api.js';
api.notebook = async () => ({items:[]});
const storage = new Map();
globalThis.localStorage = { getItem: (k) => storage.get(k) ?? null, setItem: (k,v) => storage.set(k,v) };
Object.defineProperty(globalThis, 'navigator', { configurable:true, value:{onLine:false} });
globalThis.dispatchEvent = () => {};
globalThis.CustomEvent = class { constructor(type, options) {} };
const book = { id:'book', version:'v1' }, nb = new Notebook(book);
const input = { kind:'note', start:0, end:5, quote:'Alice', text:'first', knowledge_cutoff:8 };
const n = await nb.save(input);
assert.equal(new Notebook(book).items[0].dirty,true,'offline save survives reload');
await Promise.all([nb.save({...input,text:'second'}), new Notebook(book).save({...input,text:'third'})]);
assert.equal(nb.items.length,3,'same-origin callers serialize independent note creation');
const dirty = {...n, dirty:true};
assert.equal(mergeNotes([dirty],[{...n,text:'remote',revision:9}])[0].text,'first','remote pull cannot overwrite pending local edit');
let complete;
api.saveNote = async (_id, sent) => { if (sent.id === n.id && sent.text === 'first') return new Promise(r=>complete=()=>r({item:{...sent,dirty:false,revision:1}})); return {item:{...sent,dirty:false,revision:(sent.expected_revision||0)+1}}; };
api.notebook = async () => ({items:[]});
await syncNotes('book');
navigator.onLine=true;
const syncing=syncNotes('book');
while(!complete) await new Promise(r=>setTimeout(r,1));
await nb.save({...nb.items[0],text:'edited during upload'});
complete(); await syncing;
assert.equal(nb.items.find(x=>x.id===n.id).text,'edited during upload');
assert.equal(nb.items.find(x=>x.id===n.id).revision,2,'new edit inherits acknowledged revision');
assert.equal(nb.items.find(x=>x.id===n.id).dirty,false);
navigator.onLine=false;
const conflict = await nb.save({...nb.items[0],text:'local conflict'});
api.saveNote=async()=>{throw new ConflictError('conflict',{item:{...conflict,text:'remote conflict',revision:3,dirty:false}})};
navigator.onLine=true; await syncNotes('book');
assert.equal(nb.items.find(x=>x.id===conflict.id).conflict.item.text,'remote conflict');
navigator.onLine=false; await nb.resolve(conflict.id,true);
assert(nb.items.some(x=>x.text==='local conflict' && x.id!==conflict.id));
assert(nb.items.some(x=>x.text==='remote conflict' && x.id===conflict.id));
localStorage.setItem = () => {throw Error('quota')};
await assert.rejects(nb.save(input),/尚未保存/);
console.log('notebook tests passed: durable offline drafts, serialized writers, in-flight edits, conflicts preserve both, quota never claims saved');
