"""Generate Dart Unicode compatibility tables from the frozen Python runtime."""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "core" / "lib" / "src" / "py" / "unicode_data.dart"


def ranges(values: list[int]) -> list[tuple[int, int]]:
    result = []
    for value in values:
        if result and value == result[-1][1] + 1:
            result[-1] = (result[-1][0], value)
        else:
            result.append((value, value))
    return result


def dart_string(value: str) -> str:
    out = ['"']
    for char in value:
        code = ord(char)
        if code == 0x22:
            out.append(r'\"')
        elif code == 0x5C:
            out.append(r"\\")
        elif code == 0x24:
            out.append(r"\$")
        elif 0x20 <= code <= 0x7E:
            out.append(char)
        else:
            out.append(r"\u{%x}" % code)
    out.append('"')
    return "".join(out)


def emit_ranges(name: str, values: list[int]) -> list[str]:
    result = [f"const List<(int, int)> {name} = <(int, int)>["]
    for lo, hi in ranges(values):
        result.append(f"  (0x{lo:x}, 0x{hi:x}),")
    result.append("];")
    return result


def emit_map(name: str, values: dict[int, str]) -> list[str]:
    result = [f"const Map<int, String> {name} = <int, String>{{"]
    for code, replacement in values.items():
        result.append(f"  0x{code:x}: {dart_string(replacement)},")
    result.append("};")
    return result


def main() -> None:
    all_codes = range(sys.maxunicode + 1)
    whitespace = [code for code in all_codes if chr(code).isspace()]
    digits = [code for code in all_codes if chr(code).isdigit()]
    cased = [code for code in all_codes if chr(code).lower() != chr(code).upper()]
    casefold = {code: chr(code).casefold() for code in all_codes
                if chr(code).casefold() != chr(code)}
    lower = {code: chr(code).lower() for code in all_codes
             if chr(code).lower() != chr(code)}
    title = {code: chr(code).title() for code in all_codes
             if chr(code).title() != chr(code)}
    parts = [
        "// Generated by oracle/semantics/generate_unicode.py.",
        f"// Python {sys.version_info.major}.{sys.version_info.minor}; Unicode {unicodedata.unidata_version}.",
        "// Regenerate only when the frozen Python oracle version changes.",
        "",
    ]
    for name, values in (("pyWhitespaceRanges", whitespace),
                         ("pyDigitRanges", digits), ("pyCasedRanges", cased)):
        parts.extend(emit_ranges(name, values))
        parts.append("")
    for name, values in (("pyCasefoldMap", casefold), ("pyLowerMap", lower),
                         ("pyTitleMap", title)):
        parts.extend(emit_map(name, values))
        parts.append("")
    OUT.write_text("\n".join(parts), encoding="utf-8")
    print(f"Generated {OUT.relative_to(ROOT)} using Unicode {unicodedata.unidata_version}")


if __name__ == "__main__":
    main()
