"""Emit Python module constants as Dart source, so tables stay byte-identical.

python core/tool/gen_constants.py pipeline.judge FAMILIES LEAVES ... > core/lib/src/pipeline/x_tables.dart
"""
import importlib
import json
import sys

sys.path.insert(0, '.')


def dart(v, indent=0):
    pad = '  ' * (indent + 1)
    end = '  ' * indent
    if isinstance(v, str):
        return json.dumps(v, ensure_ascii=False).replace('$', r'\$')
    if isinstance(v, bool):
        return 'true' if v else 'false'
    if v is None:
        return 'null'
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, (list, tuple)):
        if not v:
            return '<Object?>[]'
        return '<Object?>[\n' + ''.join(f'{pad}{dart(x, indent + 1)},\n' for x in v) + end + ']'
    if isinstance(v, (set, frozenset)):
        return '<Object?>{\n' + ''.join(f'{pad}{dart(x, indent + 1)},\n' for x in sorted(v)) + end + '}'
    if isinstance(v, dict):
        if not v:
            return '<String, Object?>{}'
        return '<String, Object?>{\n' + ''.join(f'{pad}{dart(k, indent + 1)}: {dart(x, indent + 1)},\n' for k, x in v.items()) + end + '}'
    raise TypeError(type(v))


def camel(name):
    parts = name.lower().split('_')
    return parts[0] + ''.join(p.title() for p in parts[1:])


mod = importlib.import_module(sys.argv[1])
print(f'// Generated by core/tool/gen_constants.py from {sys.argv[1]}; do not edit.')
print('// ignore_for_file: require_trailing_commas')
print()
for name in sys.argv[2:]:
    print(f'/// `{sys.argv[1]}.{name}`.')
    value = getattr(mod, name)
    kind = {dict: 'Map<String, Object?>', list: 'List<Object?>', tuple: 'List<Object?>', str: 'String', int: 'int', float: 'double'}.get(type(value), 'Object?')
    print(f'const {kind} {camel(name.lstrip("_"))} = {dart(value)};')
    print()
