"""Generate chapter/book policy constants from the Python oracle."""
import argparse
import json
from pathlib import Path

from pipeline import classify, kind

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'core/lib/src/pipeline/book_policy_tables.dart'


def literal(value):
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False).replace('$', r'\$')
    if isinstance(value, dict):
        return '{' + ','.join(literal(k) + ': ' + literal(v) for k, v in value.items()) + '}'
    if isinstance(value, tuple):
        return '<String>[' + ','.join(literal(v) for v in value) + ']'
    raise TypeError(type(value))


def build():
    rows = [('String', 'classifyPrompt', classify.PROMPT),
            ('Map<String, String>', 'chapterCriteria', classify.CRITERIA),
            ('Map<String, List<String>>', 'bookKinds', kind.KINDS)]
    return '// Generated by scripts/generate_book_policy_tables.py; do not edit.\n' + ''.join(
        f'const {typ} {name} = {literal(value)};\n' for typ, name, value in rows)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    content = build()
    if args.check:
        assert TARGET.read_text() == content, 'policy constants differ from Python'
    else:
        TARGET.write_text(content)
